
BATTERY_MAX_OUTPUT_POWER = 6.0
MINIMAL_BATTERY_POWER_FOR_LOAD_1 = 2.1
MINIMAL_BATTERY_POWER_FOR_LOAD_1_AND_LOAD_2 = 6.72

BATTERY_SELLING_OUTPUT = 10.0

MAX_BUYING_PRICE = 8
MIN_BUYING_PRICE = 3

PERIOD_BETWEEN_POWER_DOWN = 480
PERIOD_WITHOUT_POWER_DOWN = 450